name: .NET - Deploy AWS ECS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # tag para poder rodar manualmente

jobs:
  Build_da_Aplicacao:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup do ambiente .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x    
    
#    - name: Restore dependencies
#      run: dotnet restore
    
#    - name: Build
#      run: dotnet build --no-restore
    
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
      
#    - name: Publish
#      run: dotnet publish -c Release -o '${{ github.workspace }}/out'
      
#    - name: Zip package
#      run: |
#        cd ${{ github.workspace }}/out
#        zip -r ${{ github.workspace }}/out.zip *
    
    - name: Configurando Credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Login no Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build da imagem, tag, e push da imagem para o Amazon ECR
      env:
        ECR_REGISTRY: 137031771149.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: contador-api
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ./src/SGM.ServicosAoCidadao.Api/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG



